DIFFICULTY = {
    1: [36,37,38],
    2: [32,33,34],
    3: [28],
    4: [22,23]
}

#Game Color
GRID_COLOR = "#FFFFFF"
GAME_COLOR = "gray"

#Cell Color
EMPTY_CELL_COLOR        = "#FFFFFF"
ADJACENT_CELL_COLOR     = "#E2EBF3"
SAME_NUMBER_CELL_COLOR  = "#C3D7EA"
SELECTED_CELL_COLOR     = "#BBDEFB"
INVALID_CELL_COLOR      = "#F7CFD6"

#Number Color
DEFAULT_NUMBER_COLOR    = "#374A63"
INVALID_NUMBER_COLOR    = "#E55C6C"
VALID_NUMBER_COLOR      = "#0072E3"